---
# Kubernetes Cluster

- name: Common Parts
  hosts: all-nodes
  become: yes
  roles:
    - role: docker
    - role: common
      version: 1.25.4-00
      ip: "{{ ansible_host }}"

- name: Master
  hosts: kube-master
  become: yes
  roles:
    - role: master-kubernetes
      version: 1.25.4-00
      cidr: 192.168.0.0/16
      ip: "{{ ansible_host }}"

- name: Workers
  gather_facts: yes
  hosts: kube-nodes
  become: yes
  roles:
  - role: worker-kubernetes
    version: 1.25.4-00

# - name: Local
#   hosts: 127.0.0.1
#   connection: local
#   tasks:
#   - name: Getting Kubernetes configuration
#     local_action: copy content={{ hostvars['k8s_middle_server']['kube_config'] }} dest=mykubeconfig