---

- name: Initializing K8S master
  command: "kubeadm init --pod-network-cidr={{ cidr }} --apiserver-advertise-address={{ ip }}"

- name: Create kube directory
  file:
    path: /home/vagrant/.kube
    state: directory

- name: Setup kubeconfig for vagrant user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Kubernetes Join command  
  shell: "kubeadm token create --print-join-command"
  register: kube_join_command

- name: Print Kubernetes Join command
  debug:
    var: kube_join_command.stdout_lines

- name: Kubernetes Config  
  shell: "cat /etc/kubernetes/admin.conf"
  register: kube_config

- name: Print Kubernetes Config
  debug:
    var: kube_config.stdout_lines 

- name: "Add K8S information"
  add_host:
    name:   "{{ k8s_middle_server }}"
    kube_join_command:  "{{ kube_join_command.stdout }}"
    kube_config:   "{{ kube_config.stdout }}"